### ISSUE TITLE
Estimated Remaining Time continuously increase instead of decrease

### ISSUE THREAD

**Issue by tastyOats** [cRz-Shadows/Pokemon_Trainer_Tournament_Simulator#10]
![image](https://github.com/user-attachments/assets/16313f09-16cd-4d6e-8d6f-33785aeadff6)
 as title described! any idea if this is an issue that is resolvable? im using 4 threads alr and I'm pretty sure I only got 16 threads? 
 
![image](https://github.com/user-attachments/assets/955e4535-6b07-4116-8659-216481cfd9e7)

**Comment by cRz-Shadows** [comment]
Its estimating based on whats been run already, it is going to move around until it has enough data to properly estimate. If it hits a battle taht takes particularly longer or shorter than the last, it will move by a lot because that will impact the average time for running a battle more significantly when there's not many battles to base an average off of. That's only there for a rough estimate anyway and you're really meant to just leave it and let it run.
